# Generated by Django 5.0 on 2023-12-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortedarray',
            name='array',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sortedarray',
            name='array_name',
            field=models.CharField(error_messages={'required': 'array name must be filled'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='sortedarray',
            name='sorted_array',
            field=models.TextField(error_messages={'required': 'array must be filled'}),
        ),
    ]
