# Generated by Django 5.0 on 2023-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sortedarray_array_alter_sortedarray_array_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortedarray',
            name='array_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sortedarray',
            name='sorted_array',
            field=models.TextField(),
        ),
    ]
